config/routes.rb
Quizr::Application.routes.draw do
  root :to => "home#index"

  resources :session
  resources :users


  resources :user_quizzes, :only => [:create]

  resources :quizzes do
    resources :questions
    resources :answers
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete 'login' => 'session#destroy'

  get '/chart/user_id' => 'chart#user_id'
  get '/chart/user_lat' => 'chart#user_lat'
  get '/chart/:user_id/user_quiz_scores' => 'chart#user_quiz_scores'

  resources :user_answers, :only => [:create, :destroy]
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Quizr</a>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="/quizzes/new">Create a New Quiz</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if @current_user.nil? %>
        <li><a href="/session/new">Login</a></li>
        <li><a href="/users/new">Sign Up</a></li>
      <% else %>
        <li><a href="/users/<%= @current_user.slug %>">Your Profile</a></li>
        <li><%= link_to 'Log Out', login_path, :method => :delete %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "jquery" %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js" type="text/javascript"></script>
  <%= javascript_include_tag "application" %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Armata' rel='stylesheet' type='text/css'>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE'] %>&sensor=false" type="text/javascript"></script>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
</head>
<body>

<%= render 'layouts/nav' %>
<div id="flash">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
</div>

<div class="container">
  <%= yield %>
</div>



</body>
</html>